apiVersion: v1
kind: Secret
metadata:
  name: database-user-secret
  namespace: ${NAMESPACE}
type: Opaque
data:
  secret: "${DATABASE_USER}"
---
apiVersion: v1
kind: Secret
metadata:
  name: database-password-secret
  namespace: ${NAMESPACE}
type: Opaque
data:
  secret: "${DATABASE_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-private-key-secret
  namespace: ${NAMESPACE}
type: Opaque
data:
  secret: "${JWT_PRIVATE_KEY}"
---